### ISSUE TITLE
Array provider simply doesn't work

### ISSUE THREAD

**Issue by sonofliberty** [florianv/symfony-swap#20]
```yml
florianv_swap:
    cache:
        ttl: 7200
        type: filesystem
    providers:
        array:
            priority: 0
            rates:
                -
                    'USD/VND': 22921.00
                    'VND/USD': 0.000044
```

Converting from VND to USD will still throw an UnsupportedExchangeQueryException.

**Comment by remmel** [comment]
I agree. Indead, when constructing the PhpArray with the below config,
- latestRates = array (
  0 => 
  array (
    'EUR/GBP' => 1.5,
    'EUR/USD' => 1.1,
  ),
  1 => 
  array (
    '2017-01-01' => 
    array (
      'EUR/GBP' => 1.5,
      'EUR/USD' => 1.1,
    ),
  ),
)

historicalRate = []

Version used : florianv/swap-bundle": "^3.2"

Config:
```
  providers:
        array:
          rates:
            -
              'EUR/GBP': 1.5
              'EUR/USD': 1.1
            -
              '2017-01-01':
                'EUR/GBP': 1.5
                'EUR/USD': 1.1
```
